package com.dong.ebook.dao;

import com.dong.ebook.model.BlogType;
import com.dong.ebook.model.BlogTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BlogTypeDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_type
     *
     * @mbg.generated
     */
    long countByExample(BlogTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_type
     *
     * @mbg.generated
     */
    int deleteByExample(BlogTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_type
     *
     * @mbg.generated
     */
    int insert(BlogType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_type
     *
     * @mbg.generated
     */
    int insertSelective(BlogType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_type
     *
     * @mbg.generated
     */
    List<BlogType> selectByExample(BlogTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_type
     *
     * @mbg.generated
     */
    BlogType selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_type
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BlogType record, @Param("example") BlogTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_type
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BlogType record, @Param("example") BlogTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BlogType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BlogType record);
}