package com.dong.ebook.dao;

import com.dong.ebook.model.BookType;
import com.dong.ebook.model.BookTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BookTypeDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_type
     *
     * @mbg.generated
     */
    long countByExample(BookTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_type
     *
     * @mbg.generated
     */
    int deleteByExample(BookTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_type
     *
     * @mbg.generated
     */
    int insert(BookType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_type
     *
     * @mbg.generated
     */
    int insertSelective(BookType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_type
     *
     * @mbg.generated
     */
    List<BookType> selectByExample(BookTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_type
     *
     * @mbg.generated
     */
    BookType selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_type
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") BookType record, @Param("example") BookTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_type
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") BookType record, @Param("example") BookTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(BookType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table book_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(BookType record);
}