package com.dong.ebook.dao;

import com.dong.ebook.model.Concern;
import com.dong.ebook.model.ConcernExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConcernDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table concern
     *
     * @mbg.generated
     */
    long countByExample(ConcernExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table concern
     *
     * @mbg.generated
     */
    int deleteByExample(ConcernExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table concern
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table concern
     *
     * @mbg.generated
     */
    int insert(Concern record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table concern
     *
     * @mbg.generated
     */
    int insertSelective(Concern record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table concern
     *
     * @mbg.generated
     */
    List<Concern> selectByExample(ConcernExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table concern
     *
     * @mbg.generated
     */
    Concern selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table concern
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Concern record, @Param("example") ConcernExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table concern
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Concern record, @Param("example") ConcernExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table concern
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Concern record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table concern
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Concern record);
}