package com.dong.ebook.dao;

import com.dong.ebook.model.Music;
import com.dong.ebook.model.MusicExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MusicDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music
     *
     * @mbg.generated
     */
    long countByExample(MusicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music
     *
     * @mbg.generated
     */
    int deleteByExample(MusicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music
     *
     * @mbg.generated
     */
    int insert(Music record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music
     *
     * @mbg.generated
     */
    int insertSelective(Music record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music
     *
     * @mbg.generated
     */
    List<Music> selectByExample(MusicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music
     *
     * @mbg.generated
     */
    Music selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Music record, @Param("example") MusicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Music record, @Param("example") MusicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Music record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Music record);
}