package com.dong.ebook.dao;

import com.dong.ebook.model.MusicType;
import com.dong.ebook.model.MusicTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MusicTypeDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_type
     *
     * @mbg.generated
     */
    long countByExample(MusicTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_type
     *
     * @mbg.generated
     */
    int deleteByExample(MusicTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_type
     *
     * @mbg.generated
     */
    int insert(MusicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_type
     *
     * @mbg.generated
     */
    int insertSelective(MusicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_type
     *
     * @mbg.generated
     */
    List<MusicType> selectByExample(MusicTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_type
     *
     * @mbg.generated
     */
    MusicType selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_type
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MusicType record, @Param("example") MusicTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_type
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MusicType record, @Param("example") MusicTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MusicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table music_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MusicType record);
}