package com.dong.ebook.dao;

import com.dong.ebook.model.PageView;
import com.dong.ebook.model.PageViewExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PageViewDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_view
     *
     * @mbg.generated
     */
    long countByExample(PageViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_view
     *
     * @mbg.generated
     */
    int deleteByExample(PageViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_view
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_view
     *
     * @mbg.generated
     */
    int insert(PageView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_view
     *
     * @mbg.generated
     */
    int insertSelective(PageView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_view
     *
     * @mbg.generated
     */
    List<PageView> selectByExample(PageViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_view
     *
     * @mbg.generated
     */
    PageView selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_view
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PageView record, @Param("example") PageViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_view
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PageView record, @Param("example") PageViewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_view
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PageView record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_view
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PageView record);
}