package com.dong.ebook.dao;

import com.dong.ebook.model.PictureType;
import com.dong.ebook.model.PictureTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PictureTypeDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_type
     *
     * @mbg.generated
     */
    long countByExample(PictureTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_type
     *
     * @mbg.generated
     */
    int deleteByExample(PictureTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_type
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_type
     *
     * @mbg.generated
     */
    int insert(PictureType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_type
     *
     * @mbg.generated
     */
    int insertSelective(PictureType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_type
     *
     * @mbg.generated
     */
    List<PictureType> selectByExample(PictureTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_type
     *
     * @mbg.generated
     */
    PictureType selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_type
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PictureType record, @Param("example") PictureTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_type
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PictureType record, @Param("example") PictureTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PictureType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture_type
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PictureType record);
}