package com.dong.ebook.dao;

import com.dong.ebook.model.Preference;
import com.dong.ebook.model.PreferenceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PreferenceDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference
     *
     * @mbg.generated
     */
    long countByExample(PreferenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference
     *
     * @mbg.generated
     */
    int deleteByExample(PreferenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference
     *
     * @mbg.generated
     */
    int insert(Preference record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference
     *
     * @mbg.generated
     */
    int insertSelective(Preference record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference
     *
     * @mbg.generated
     */
    List<Preference> selectByExample(PreferenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference
     *
     * @mbg.generated
     */
    Preference selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") Preference record, @Param("example") PreferenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") Preference record, @Param("example") PreferenceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Preference record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table preference
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Preference record);
}