package com.dong.ebook.model;

public class BlogWithBLOBs extends Blog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog.content_html
     *
     * @mbg.generated
     */
    private String contentHtml;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.content
     *
     * @return the value of blog.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.content
     *
     * @param content the value for blog.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog.content_html
     *
     * @return the value of blog.content_html
     *
     * @mbg.generated
     */
    public String getContentHtml() {
        return contentHtml;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog.content_html
     *
     * @param contentHtml the value for blog.content_html
     *
     * @mbg.generated
     */
    public void setContentHtml(String contentHtml) {
        this.contentHtml = contentHtml == null ? null : contentHtml.trim();
    }
}