package com.dong.ebook.model;

public class BookType {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_type.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_type.class_num
     *
     * @mbg.generated
     */
    private String classNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book_type.class_name
     *
     * @mbg.generated
     */
    private String className;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_type.id
     *
     * @return the value of book_type.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_type.id
     *
     * @param id the value for book_type.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_type.class_num
     *
     * @return the value of book_type.class_num
     *
     * @mbg.generated
     */
    public String getClassNum() {
        return classNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_type.class_num
     *
     * @param classNum the value for book_type.class_num
     *
     * @mbg.generated
     */
    public void setClassNum(String classNum) {
        this.classNum = classNum == null ? null : classNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book_type.class_name
     *
     * @return the value of book_type.class_name
     *
     * @mbg.generated
     */
    public String getClassName() {
        return className;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book_type.class_name
     *
     * @param className the value for book_type.class_name
     *
     * @mbg.generated
     */
    public void setClassName(String className) {
        this.className = className == null ? null : className.trim();
    }
}