package com.dong.ebook.model;

public class BookWithBLOBs extends Book {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.catalog
     *
     * @mbg.generated
     */
    private String catalog;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column book.introduction
     *
     * @mbg.generated
     */
    private String introduction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.catalog
     *
     * @return the value of book.catalog
     *
     * @mbg.generated
     */
    public String getCatalog() {
        return catalog;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.catalog
     *
     * @param catalog the value for book.catalog
     *
     * @mbg.generated
     */
    public void setCatalog(String catalog) {
        this.catalog = catalog == null ? null : catalog.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column book.introduction
     *
     * @return the value of book.introduction
     *
     * @mbg.generated
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column book.introduction
     *
     * @param introduction the value for book.introduction
     *
     * @mbg.generated
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }
}