package com.dong.ebook.model;

import java.util.Date;

public class Music {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.file_url
     *
     * @mbg.generated
     */
    private String fileUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.cover_url
     *
     * @mbg.generated
     */
    private String coverUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.author
     *
     * @mbg.generated
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.composer
     *
     * @mbg.generated
     */
    private String composer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.singer
     *
     * @mbg.generated
     */
    private String singer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.music_type_id
     *
     * @mbg.generated
     */
    private Long musicTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.modify_user_id
     *
     * @mbg.generated
     */
    private Long modifyUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.traffic
     *
     * @mbg.generated
     */
    private Integer traffic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column music.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.id
     *
     * @return the value of music.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.id
     *
     * @param id the value for music.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.file_url
     *
     * @return the value of music.file_url
     *
     * @mbg.generated
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.file_url
     *
     * @param fileUrl the value for music.file_url
     *
     * @mbg.generated
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl == null ? null : fileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.cover_url
     *
     * @return the value of music.cover_url
     *
     * @mbg.generated
     */
    public String getCoverUrl() {
        return coverUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.cover_url
     *
     * @param coverUrl the value for music.cover_url
     *
     * @mbg.generated
     */
    public void setCoverUrl(String coverUrl) {
        this.coverUrl = coverUrl == null ? null : coverUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.name
     *
     * @return the value of music.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.name
     *
     * @param name the value for music.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.author
     *
     * @return the value of music.author
     *
     * @mbg.generated
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.author
     *
     * @param author the value for music.author
     *
     * @mbg.generated
     */
    public void setAuthor(String author) {
        this.author = author == null ? null : author.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.composer
     *
     * @return the value of music.composer
     *
     * @mbg.generated
     */
    public String getComposer() {
        return composer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.composer
     *
     * @param composer the value for music.composer
     *
     * @mbg.generated
     */
    public void setComposer(String composer) {
        this.composer = composer == null ? null : composer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.singer
     *
     * @return the value of music.singer
     *
     * @mbg.generated
     */
    public String getSinger() {
        return singer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.singer
     *
     * @param singer the value for music.singer
     *
     * @mbg.generated
     */
    public void setSinger(String singer) {
        this.singer = singer == null ? null : singer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.music_type_id
     *
     * @return the value of music.music_type_id
     *
     * @mbg.generated
     */
    public Long getMusicTypeId() {
        return musicTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.music_type_id
     *
     * @param musicTypeId the value for music.music_type_id
     *
     * @mbg.generated
     */
    public void setMusicTypeId(Long musicTypeId) {
        this.musicTypeId = musicTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.modify_user_id
     *
     * @return the value of music.modify_user_id
     *
     * @mbg.generated
     */
    public Long getModifyUserId() {
        return modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.modify_user_id
     *
     * @param modifyUserId the value for music.modify_user_id
     *
     * @mbg.generated
     */
    public void setModifyUserId(Long modifyUserId) {
        this.modifyUserId = modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.traffic
     *
     * @return the value of music.traffic
     *
     * @mbg.generated
     */
    public Integer getTraffic() {
        return traffic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.traffic
     *
     * @param traffic the value for music.traffic
     *
     * @mbg.generated
     */
    public void setTraffic(Integer traffic) {
        this.traffic = traffic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.create_time
     *
     * @return the value of music.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.create_time
     *
     * @param createTime the value for music.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column music.modify_time
     *
     * @return the value of music.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column music.modify_time
     *
     * @param modifyTime the value for music.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}