package com.dong.ebook.model;

import java.util.Date;

public class PageView {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page_view.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page_view.number
     *
     * @mbg.generated
     */
    private Long number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page_view.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column page_view.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page_view.id
     *
     * @return the value of page_view.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page_view.id
     *
     * @param id the value for page_view.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page_view.number
     *
     * @return the value of page_view.number
     *
     * @mbg.generated
     */
    public Long getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page_view.number
     *
     * @param number the value for page_view.number
     *
     * @mbg.generated
     */
    public void setNumber(Long number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page_view.create_time
     *
     * @return the value of page_view.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page_view.create_time
     *
     * @param createTime the value for page_view.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column page_view.modify_time
     *
     * @return the value of page_view.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column page_view.modify_time
     *
     * @param modifyTime the value for page_view.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}