package com.dong.ebook.model;

import java.util.Date;

public class Picture {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.file_url
     *
     * @mbg.generated
     */
    private String fileUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.picture_type_id
     *
     * @mbg.generated
     */
    private Long pictureTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.modify_user_id
     *
     * @mbg.generated
     */
    private Long modifyUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.traffic
     *
     * @mbg.generated
     */
    private Integer traffic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.modify_time
     *
     * @mbg.generated
     */
    private Date modifyTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.id
     *
     * @return the value of picture.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.id
     *
     * @param id the value for picture.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.title
     *
     * @return the value of picture.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.title
     *
     * @param title the value for picture.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.file_url
     *
     * @return the value of picture.file_url
     *
     * @mbg.generated
     */
    public String getFileUrl() {
        return fileUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.file_url
     *
     * @param fileUrl the value for picture.file_url
     *
     * @mbg.generated
     */
    public void setFileUrl(String fileUrl) {
        this.fileUrl = fileUrl == null ? null : fileUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.picture_type_id
     *
     * @return the value of picture.picture_type_id
     *
     * @mbg.generated
     */
    public Long getPictureTypeId() {
        return pictureTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.picture_type_id
     *
     * @param pictureTypeId the value for picture.picture_type_id
     *
     * @mbg.generated
     */
    public void setPictureTypeId(Long pictureTypeId) {
        this.pictureTypeId = pictureTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.modify_user_id
     *
     * @return the value of picture.modify_user_id
     *
     * @mbg.generated
     */
    public Long getModifyUserId() {
        return modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.modify_user_id
     *
     * @param modifyUserId the value for picture.modify_user_id
     *
     * @mbg.generated
     */
    public void setModifyUserId(Long modifyUserId) {
        this.modifyUserId = modifyUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.traffic
     *
     * @return the value of picture.traffic
     *
     * @mbg.generated
     */
    public Integer getTraffic() {
        return traffic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.traffic
     *
     * @param traffic the value for picture.traffic
     *
     * @mbg.generated
     */
    public void setTraffic(Integer traffic) {
        this.traffic = traffic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.create_time
     *
     * @return the value of picture.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.create_time
     *
     * @param createTime the value for picture.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.modify_time
     *
     * @return the value of picture.modify_time
     *
     * @mbg.generated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.modify_time
     *
     * @param modifyTime the value for picture.modify_time
     *
     * @mbg.generated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }
}